name: Create PR on successful tests

on:
 workflow_dispatch:   # <- Mauvaise indentation volontaire ici

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout integration branch
        uses: actions/checkout@v3
        with:
          ref: integration
