name: Debug Workflow Run

on:
  workflow_run:
    workflows: ["Test Angular Front"]
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow_run triggered successfully!"
