name: Cypress E2E Tests

on:
  push:
    branches: [integration]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./manga-up-front  

      - name: Start Angular app
        run: npm run start &
        working-directory: ./manga-up-front  

      - name: Wait for app to be available
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./manga-up-front

      - name: Upload Cypress screenshots/videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            ./manga-up-front/cypress/screenshots/
            ./manga-up-front/cypress/videos/
